top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/metadata
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/metadata
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/metadata

include $(top_srcdir)/build/special.mk

