top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/loggers
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/loggers
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/loggers

include $(top_srcdir)/build/special.mk

