top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/os
builddir     = /home/salman/DPP/data/httpd-2.4.7/os
VPATH        = /home/salman/DPP/data/httpd-2.4.7/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
