top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/http
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/http
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/http

include $(top_srcdir)/build/special.mk

