top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/generators
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/generators
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/generators

include $(top_srcdir)/build/special.mk

