top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/aaa
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/aaa
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/aaa

include $(top_srcdir)/build/special.mk

