top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/arch/unix
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/arch/unix
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/arch/unix

include $(top_srcdir)/build/special.mk

