top_srcdir   = /home/salman/DPP/data/httpd-2.4.7
top_builddir = /home/salman/DPP/data/httpd-2.4.7
srcdir       = /home/salman/DPP/data/httpd-2.4.7/modules/debugging
builddir     = /home/salman/DPP/data/httpd-2.4.7/modules/debugging
VPATH        = /home/salman/DPP/data/httpd-2.4.7/modules/debugging
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
